spring:
  application:
    name: BookRecord

  main:
    allow-bean-definition-overriding: true

  datasource:
    url: jdbc:mysql://localhost:3306/BookRecord?serverTimezone=UTC&characterEncoding=UTF-8
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: do0@960201

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
    database: mysql

  jwt:
    secret: "emVyb2Jhc2UtcGVyc29uYWwtcHJvamVjdC1ib29rLXJlY29yZC1zeXN0ZW0="