spring:
  application:
    name: BookRecord

  datasource:
    url: jdbc:mysql://localhost:3306/BookRecord?serverTimezone=UTC&characterEncoding=UTF-8
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: do0@960201

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
    database: mysql

  jwt:
    secret: "Ym9vay1yZWNvcmQtc2VydmljZS1wcm9qZWN0Cg=="